package codes.draeger.kontrakt.core.generator

import codes.draeger.kontrakt.core.model.ApiDefinition
import codes.draeger.kontrakt.core.model.DataType
import codes.draeger.kontrakt.core.model.SchemaDefinition
import codes.draeger.kontrakt.core.model.SchemaField
import codes.draeger.kontrakt.core.model.Validator
import java.time.LocalDateTime

public class TypeScriptGenerator {

    public fun generate(api: ApiDefinition): String {
        val sb = StringBuilder()
        sb.append("// GENERATED BY KONTRAKT\n")
        sb.append("// Time: ${LocalDateTime.now()}\n")
        sb.append("import { z } from 'zod';\n")
        sb.append("import { os } from '@orpc/server';\n\n")

        /**
         * DTOs
         */
        api.schemas.forEach { schema ->
            generateZodSchema(schema, sb)
        }

        /**
         * router
         */
        sb.append("export const contract = {\n")

        val routeStrings = api.routes.map { route ->
            """
            |  ${route.operationId}: os.route({
            |    method: '${route.method}',
            |    path: '${route.path}'
            |  })
            |    .input(${renderType(route.inputType)})
            |    .output(${renderType(route.outputType)})
            """.trimMargin()
        }

        sb.append(routeStrings.joinToString(",\n"))
        sb.append("\n};\n")

        return sb.toString()
    }

    private fun generateZodSchema(schema: SchemaDefinition, sb: StringBuilder) {
        val schemaName = "${schema.name}Schema"
        sb.append("export const $schemaName = z.object({\n")

        val fields = schema.fields.joinToString(",\n") { field ->
            val baseZod = renderType(field.type)
            val withValidators = applyValidators(baseZod, field)
            "  ${field.name}: $withValidators"
        }

        sb.append(fields)
        sb.append("\n});\n")
        sb.append("export type ${schema.name} = z.infer<typeof $schemaName>;\n\n")
    }

    private fun renderType(type: DataType): String {
        return when (type) {
            DataType.StringType -> "z.string()"
            DataType.NumberType -> "z.number()"
            DataType.BooleanType -> "z.boolean()"
            DataType.VoidType -> "z.void()"
            DataType.AnyType -> "z.any()"
            is DataType.ReferenceType -> "${type.schemaName}Schema"
            is DataType.ArrayType -> "z.array(${renderType(type.wrapped)})"
        }
    }

    private fun applyValidators(zodString: String, field: SchemaField): String {
        var res = zodString
        field.validators.forEach { v ->
            res = when (v) {
                is Validator.Email -> "$res.email()"
                is Validator.Min -> "$res.min(${v.value})"
                is Validator.Max -> "$res.max(${v.value})"
                is Validator.MinLength -> "$res.min(${v.value})"
                is Validator.MaxLength -> "$res.max(${v.value})"
            }
        }
        if (field.isNullable) res = "$res.nullable()"
        return res
    }
}
